services:
  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:8000"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - USER_SERVICE_URL=http://user-service:8000
      - JOB_SERVICE_URL=http://job-service:8000
      - APPLICATION_SERVICE_URL=http://application-service:8000

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"

  user-service:
    build: ./user-service
    ports:
      - "8002:8000"

  job-service:
    build: ./job-service
    ports:
      - "8003:8000"

  application-service:
    build: ./application-service
    ports:
      - "8004:8000"
